### ISSUE TITLE
[BUG] get_avatar_url() uses gravatar

### ISSUE THREAD

**Issue by Morpheus636** [MatteoManna/Simple-User-Avatar#9]
Calling `get_avatar_url($ID)` still returns Gravatar instead of local image.

**Comment by xpdoc** [comment]
Probably fixed in #10.

@MatteoManna any chance in getting it merged?

**Comment by MatteoManna** [comment]
Hi @xpdoc,
I merged your fix, I will release 4.7 in a minutes.

Thank you.

**Comment by jorgeEF** [comment]
get_avatar_url($user_id) still gets gravatar image instead of the simple-user-avatar uploaded image.
